title: Daniel Freeland
description: Daniel Freeland is a college professor and recent graduate of Cal State University East Bay's M.S. Statistics Program. 
github_username: Daniel-Freeland
theme: jekyll-theme-leap-day
